config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, :controllers => { registrations: 'registrations' }
  get 'home/index'
  get 'products/index'
  get 'devise/user_session'
  get 'devise/destroy_user_session'

  resources :products
  resources :devise
  resources :charges
  resources :orders
  resources :profiles, only: [:index]

  resources :images, only: [:index, :new, :create, :destroy]

  root 'home#index'
end

app/views/shared/_header.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Car Group Buys
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}

  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      %a.navbar-brand{:href => "/home/index"} Car Group Buys
      %button.navbar-toggler{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarText", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarText.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            %a.nav-link{:href => "/products/index"} Products
          %li.nav-item
            %a.nav-link{:href => "#"} Contact
          - if customer_signed_in?
            %li.nav-item
            = link_to "Profile", profiles_path, class: "nav-link"

        - if customer_signed_in?
          = form_tag(products_path, method: :get, class: "form-inline my-2 my-lg-0") do
            = text_field_tag :term, params[:term], class: "form-control mr-sm-2", placeholder: "Search"
            = submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0"
          = link_to('Logout', destroy_customer_session_path, method: :delete, class: "btn btn-primary")
        - else
          = link_to('Login', new_customer_session_path, class: "btn btn-style")

app/views/shared/_index.html.haml
.tab-pane
  .container
    - if customer_signed_in?
      %br
        - if current_customer.admin?
          = link_to 'Add product', new_product_path(@product), class: "btn btn-primary"
      %br
      .row
        .span4
        - @products.each do |product|
          - if Date.today <= product.product_end_date
            %br
            .card{:style => "width: 20rem;"}
              .card-block
                %h4= product.title
                = image_tag product.image_url, class: "small" rescue nil
                %p.card-text= product.description
                %h4
                  $
                  = product.variable_price

              = link_to 'More details', product_path(product), class: "btn btn-primary"