config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, :controllers => { registrations: 'registrations' }
  get 'home/index'
  get 'products/index'
  get 'devise/user_session'
  get 'devise/destroy_user_session'

  resources :products
  resources :devise
  resources :charges
  resources :orders
  resources :profiles, only: [:index]

  resources :images, only: [:index, :new, :create, :destroy]

  root 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders

  scope :active, -> { where(active: true) }

  def self.search(term)
    if term
      where('title LIKE ?', "%#{term}%").order('product_id DESC')
    else
      order('product_id DESC')
    end
  end

  def variable_price
    order_qty = Order.where(product_id: self.id).sum(:quantity)

    if order_qty < self.cheaper_target
      best_price = self.price
    elsif order_qty >= self.cheaper_target && order_qty < self.cheapest_target
      best_price = self.cheaper_price
    else
      best_price = self.cheapest_price
    end

    return best_price
  end


  mount_uploader :image, ImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.active.search(params[:term])
  end

  def show
    @product = Product.find(params[:id])
    @order = Order.new
    @customer = current_customer
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.update_attributes(active: false)

    redirect_to home_index_path
  end



  private
  def product_params
    params.require(:product).permit(:product_id, :customer_id, :title, :description, :price, :manufacturer, :model, :brand, :image, :cheaper_target,
                                    :cheaper_price, :cheapest_target, :cheapest_price, :term, :product_end_date)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
= form_for @product, html: { multipart: true } do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this pet from being saved:
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  %br
    = f.text_field :title
  %br
    = f.text_field :description
  %br
    = f.text_field :image
  %br
    = f.text_field :brand
  %br
    = f.text_field :manufacturer
  %br
    = f.text_field :model
  %br
    = f.text_field :price
  %p
    = f.text_field :price, placeholder: "Starting Price"
    %h5 Enter number of sales to unlock the cheaper price
    = f.text_field :cheaper_target, placeholder: "Target sales"
    = f.text_field :cheaper_price, placeholder: "Cheaper Price"
    %h5 Enter number of sales to unlock the cheapest price
    = f.text_field :cheapest_target, placeholder: "Target sales"
    = f.text_field :cheapest_price, placeholder: "Cheapest Price"
  %p
    = f.text_field :product_end_date, placeholder: "What date should the product end?"
    %br
  %p.actions
    %br
    = link_to "Cancel", products_path, class: "form-cancel"
    = f.submit "Save", class: "form-submit"

app/views/products/index.html.haml
=render :partial => 'shared/index'

app/views/products/new.html.haml
- if customer_signed_in?
  = form_for @product, id: "myForm", html: { multipart: true } do |f|
    - if @product.errors.any?
      #error_explanation
        %h2
          = pluralize(@product.errors.count, "error")
          prohibited this product from being saved:
        %ul
          - @product.errors.full_messages.each do |message|
            %li= message

    %br
      = f.text_field :title, placeholder: "Title", required: true
      %br
      %br
    %p
      = f.text_field :description, placeholder: "Description", required: true
      %br
      %br
      %br
    %p.center
      %h2 Upload Image
      %br
    %p.center
      .field
        = f.file_field :image
      %br
      %br
    %p
      = f.text_field :brand, placeholder: "Brand"
      %br
      %br
    -#  = f.text_field :manufacturer, placeholder: "Manufacturer"
    -#  %br
    -#  %br
    -#%p
    -#  = f.text_field :model, placeholder: "Model"
    -#  %br
    %p#number-error-dialog
      = f.text_field :price, placeholder: "Starting Price", required: true, "data-validation" =>"number"
      %h5 Enter number of sales to unlock the cheaper price
    %p#number-error-dialog
      = f.text_field :cheaper_target, placeholder: "Target sales", "data-validation" =>"number"
      = f.text_field :cheaper_price, placeholder: "Cheaper Price", "data-validation" =>"number"
      %h5 Enter number of sales to unlock the cheapest price
    %p#number-error-dialog
      = f.text_field :cheapest_target, placeholder: "Target sales", "data-validation" =>"number"
      = f.text_field :cheapest_price, placeholder: "Cheapest Price", "data-validation" =>"number"
      %br
    %p
      %h5 What date should the product end?
      #date-error-dialog
        = f.text_field :product_end_date, placeholder: "YYYY-MM-DD", required: true, "data-validation" => "date", "data-validation-format" => "yyyy-mm-dd"
      %br
      %br
      %br
      = f.hidden_field :customer_id, value: current_customer.id

    %p.actions
      %br
      = link_to "Cancel", products_path, class: "form-cancel"
      = f.submit "Save", class: "form-submit"
      #target.thumbnail


%script{:src => "//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"}

:javascript
  $.validate({
  });

app/views/products/show.html.haml
#body
  .center
    %span.box1.box2
      %h2.space-50= @product.title
  %table.center.space-50
    %tr
      %td= image_tag(@product.image_url(:thumb).to_s)
      %td= @product.description
    %tr
      %td
      %td= @product.brand
    %tr
      %td
      %td= @product.manufacturer
    %tr
      %td
      %td= @product.model
  .center.space-50
    %h3 Price
    %h3
      $
      = @product.variable_price
    - if current_customer.admin? && current_customer.id == @product.customer_id
      = link_to 'Edit', controller: "products", action: "edit", product: @product.id
      = link_to 'Delete', product_path(@product), method: :delete

= form_for @order, :url => orders_path, :html => {:method => :post} do |f|
  - if @order.errors.any?
    #error_explanation
      %h2
        = pluralize(@order.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  %p.center.space-20
    = f.label :quantity
    %br
    = f.number_field :quantity, "data-validation"=>"length", "data-validation-length"=> "min1"
    %br
    = f.hidden_field :product_id, value: @product.id
    = f.hidden_field :customer_id, value: @customer.customer_id

  %p.actions.center
    %br
    %script.stripe-button{ src: "https://checkout.stripe.com/checkout.js",
          data: {amount: @product.variable_price * 100, description: @product.title, email: @customer.email, key: Rails.configuration.stripe[:publishable_key]}}


%script{:src => "//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"}

:javascript
  var quantityAmount = #{@product.variable_price}
  $.validate({
  });

  $("#order_quantity").on("keyup", function(){
    var quantityValue = $(this).val();
    k = (parseInt(quantityValue) * quantityAmount) * 100;

    $('.stripe-button').attr('data-amount', k)
  })